### ISSUE TITLE
500 error "Navigation timeout of 30000 ms exceeded"

### ISSUE THREAD

**Issue by sideshowbarker** [w3c/spec-generator#284] opened 2020-03-06 03:43 UTC
```
$ curl -i "https://labs.w3.org/spec-generator/?type=respec&url=https://mathml-refresh.github.io/mathml-core/"
HTTP/2 500
x-powered-by: Express
content-type: application/json; charset=utf-8
content-length: 51
etag: W/"33-B9tscI3tM+SOKGsBsSIaNUqebh8"
date: Fri, 06 Mar 2020 03:43:06 GMT
strict-transport-security: max-age=15552015; preload
public-key-pins: pin-sha256="cN0QSpPIkuwpT6iP2YjEo1bEwGpH/yiUn6yhdy+HNto="; pin-sha256="WGJkyYjx1QMdMe0UqlyOKXtydPDVrk7sl2fV+nNm1r4="; pin-sha256="LrKdTxZLRTvyHM4/atX2nquX9BeHRZMCxg3cf4rhc2I="; max-age=864000

{"error":"Navigation timeout of 30000 ms exceeded"}
```

This currently seems to be happening regardless of what spec URL I give to the generator.

**Comment by marcoscaceres** [comment] 2020-03-06 05:04
odd... maybe the spec generator's respec is out of date?

**Comment by jnurthen** [comment] 2020-03-13 18:47
Can someone look at this - all our specs are broken.

**Comment by carmacleod** [comment] 2020-03-13 19:02
[Timeout was changed from 2 seconds to 3 seconds a year ago](https://github.com/w3c/spec-generator/commit/685b0cdbcf793bf014fdcca4932d4c2e15bbb2d6)... maybe it needs to be bumped up to 4 seconds? (I have no clue - just making wild guesses... 😄 )

**Comment by marcoscaceres** [comment] 2020-03-16 06:00
Poked around a little bit. The reason is failing is that the `data-include=`s are breaking for some reason. We will need to do some debugging to figure out why. The quick fix is to make the `data-include`s into absolute URLs... so, for example:

```
<pre data-include="https://mathml-refresh.github.io/mathml-core/user-agent-stylesheet/mtable.css"></pre>
```

CC @sidvishnoi.

**Comment by sideshowbarker** [comment] 2020-03-16 06:18
If I `git clone https://github.com/w3c/spec-generator.git; cd spec-generator; npm run start` it runs for me locally as expected, without the *“Navigation timeout of 30000 ms exceeded”*.

I’m curious why it would run as expected locally, even though the remote instance fails.

**Comment by sidvishnoi** [comment] 2020-03-16 10:34
I tried locally, as well as using https://labs.w3.org/spec-generator. Worked fine for me.
I've seen this error in past due to the network conditions - at the client side, as well as at w3.org - which hosts the ReSpec script. (and I was able to simulate this with a slow network.)
Can anyone confirm if the issue still persists? I'll investigate further.

**Comment by sideshowbarker** [comment] 2020-03-16 10:57
> Can anyone confirm if the issue still persists?

I can’t reproduce it now

> I've seen this error in past due to the network conditions - at the client side, as well as at w3.org

OK, yeah, then I guess what’s most likely is that there was some problem with the network conditions on the w3.org side — rather than on the client side for anybody individually (because if it were client-side network issue, it seems we wouldn’t have multiple people running into the problem at the same time).

**Comment by marcoscaceres** [comment] 2020-03-16 11:45
Yeah, same... can't reproduce.

**Comment by marcoscaceres** [comment] 2020-03-16 11:46
Ignore what I said above (https://github.com/w3c/spec-generator/issues/284#issuecomment-599359533) also. That only really helps with respec2html locally, but works fine.

**Comment by deniak** [comment] 2020-03-16 12:43
Sorry, I missed that issue earlier. I redeployed spec-generator with the latest version of respec. It seems to work fine now. @sideshowbarker can you confirm?

**Comment by marcoscaceres** [comment] 2020-03-16 12:44
Not @sideshowbarker, but WFM with curl.

**Comment by sideshowbarker** [comment] 2020-03-16 13:04
Yup — working as expected for me too

**Comment by deniak** [comment] 2020-03-16 13:08
Ok, thanks for the confirmations. I'll close this ticket for now then.

**Closed by deniak** 2020-03-16 13:08 UTC
